[versions]
agp = "8.2.0-alpha12"
kotlin = "1.9.10"
compose = "1.5.10-beta02"
activity-compose = "1.8.0"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-mulitplatform = { id = "org.jetbrains.compose", version.ref = "compose" }